"""
app.py
-------
Streamlit dashboard for the Electricity Theft Detection project.

Run with:
    streamlit run app/app.py

The dashboard reads the pre-scored dataset (data/scored_customers.csv)
that is generated by src/train_model.py, so make sure that script has
been run at least once before starting the dashboard.
"""

import os
import sys

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Allow importing from src/
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))
from prediction import load_scored_customers, get_customer_summary, get_latest_record, format_customer_report, _fmt  # noqa: E402
from evaluate_model import record_level_summary, customer_level_summary  # noqa: E402

sns.set_style("whitegrid")

BASE_DIR = os.path.dirname(__file__)
DATA_PATH = os.path.join(BASE_DIR, "..", "data", "scored_customers.csv")

MODELS_DIR = os.path.join(BASE_DIR, "..", "models")
COMPARISON_PATH = os.path.join(BASE_DIR, "..", "data", "model_comparison.csv")
EVAL_SUMMARY_PATH = os.path.join(MODELS_DIR, "evaluation_summary.pkl")

st.set_page_config(page_title="Electricity Theft Detection", layout="wide")


@st.cache_data
def load_data():
    return load_scored_customers(DATA_PATH)


@st.cache_data
def load_comparison_table():
    if os.path.exists(COMPARISON_PATH):
        return pd.read_csv(COMPARISON_PATH)
    return None


@st.cache_data
def load_eval_summary():
    if os.path.exists(EVAL_SUMMARY_PATH):
        import joblib
        return joblib.load(EVAL_SUMMARY_PATH)
    return None


def main():
    st.title("⚡ Electricity Theft Detection Dashboard")
    st.caption(
        "A machine-learning decision-support tool that flags consumption patterns for "
        "further human investigation. This is a student project using synthetic data — "
        "it does not prove theft and is not connected to any real utility system."
    )
    st.info(
        "**Important:** An anomalous consumption pattern does not necessarily indicate "
        "electricity theft. It may occur because of vacations, seasonal changes, vacant "
        "properties, solar panels, business closures, meter faults, or other legitimate "
        "reasons. This system is an early-warning / decision-support tool — it "
        "identifies patterns that *may* indicate potential theft and prioritizes them "
        "for further investigation. It does not make a final accusation of theft."
    )

    if not os.path.exists(DATA_PATH):
        st.error(
            "Scored dataset not found. Please run `python src/train_model.py` first "
            "to generate the dataset and train the models."
        )
        return

    df = load_data()

    tab1, tab2, tab3, tab4 = st.tabs(
        ["🏠 Dashboard Home", "🔍 Customer Analysis", "📊 Data Visualization", "⚖️ Model Comparison"]
    )

    with tab1:
        show_home(df)

    with tab2:
        show_customer_analysis(df)

    with tab3:
        show_visualizations(df)

    with tab4:
        show_model_comparison()


def show_home(df: pd.DataFrame):
    st.subheader("Overview")
    st.caption(
        "**Primary model:** Isolation Forest (unsupervised anomaly detection). "
        "One-Class SVM and Random Forest are shown for comparison only — see the "
        "'Model Comparison' tab."
    )

    rec = record_level_summary(df)
    cust = customer_level_summary(df)

    train_months = sorted(df.loc[df["Data_Split"] == "Train", "Month"].unique())
    test_months = sorted(df.loc[df["Data_Split"] == "Test", "Month"].unique())
    st.caption(
        f"Models were trained on historical months {train_months} and evaluated on "
        f"unseen months {test_months} — a time-based split that mirrors how the system "
        f"would be used in practice (train on the past, score new data)."
    )

    st.markdown("#### Record-Level (per customer-month)")
    col1, col2, col3, col4, col5 = st.columns(5)
    col1.metric("Total Customer-Months", f"{rec['total_records']:,}")
    col2.metric("Normal", f"{rec['normal_records']:,}")
    col3.metric("Suspicious", f"{rec['suspicious_records']:,}")
    col4.metric("High Risk", f"{rec['high_risk_records']:,}")
    col5.metric("Record Anomaly Rate", f"{rec['record_anomaly_rate_pct']:.2f}%")
    st.caption(
        "This is the share of *individual monthly records* flagged. A customer with 6 "
        "months of history contributes up to 6 records — one flagged month does not "
        "mean the customer overall is high-risk. See customer-level metrics below."
    )

    st.markdown("#### Customer-Level (unique customers)")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Unique Customers", f"{cust['total_customers']:,}")
    col2.metric("With ≥1 Suspicious Month", f"{cust['customers_with_suspicious_month']:,}")
    col3.metric("With ≥1 High-Risk Month", f"{cust['customers_with_high_risk_month']:,}")
    col4.metric("Customer Risk Rate", f"{cust['customer_risk_rate_pct']:.2f}%")
    st.caption(
        f"{cust['customers_flagged_at_least_once']:,} of {cust['total_customers']:,} "
        f"unique customers had at least one Suspicious or High-Risk month "
        f"({cust['customer_risk_rate_pct']:.2f}%). This is the more meaningful "
        f"number for deciding how many actual customers might need investigation."
    )

    st.markdown("---")
    st.markdown(
        """
        **Important:** These categories are early-warning indicators generated from
        consumption-pattern anomalies. A "Suspicious" or "High Risk" label means the
        pattern is *statistically unusual*, not that theft has been confirmed. Legitimate
        reasons (vacation, vacant property, seasonal change, solar installation, business
        closure, meter malfunction) can also produce these patterns. Final decisions should
        always involve human investigation.
        """
    )

    st.markdown("### Risk Level Distribution")
    fig, ax = plt.subplots(figsize=(6, 3))
    order = ["Normal", "Suspicious", "High Risk"]
    colors = ["#4C9A6A", "#E8B84B", "#D1495B"]
    sns.countplot(data=df, x="Risk_Level", order=order, hue="Risk_Level", palette=colors, legend=False, ax=ax)
    ax.set_xlabel("")
    ax.set_ylabel("Number of Records")
    st.pyplot(fig)


def show_customer_analysis(df: pd.DataFrame):
    st.subheader("Customer-Level Analysis")

    customer_ids = sorted(df["Customer_ID"].unique())
    customer_id = st.selectbox("Select Customer ID", customer_ids)

    history = get_customer_summary(df, customer_id)
    latest = get_latest_record(df, customer_id)

    if latest is None:
        st.warning("No data found for this customer.")
        return

    risk_color = {"Normal": "green", "Suspicious": "orange", "High Risk": "red"}[latest["Risk_Level"]]

    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown(f"#### Customer: `{customer_id}`")
        st.markdown(f"**Risk Level:** :{risk_color}[{latest['Risk_Level'].upper()}]")
        st.write(f"Previous 6-Month Average Consumption: **{_fmt(latest['Average_Consumption_6_Months'], ' kWh')}**")
        st.write(f"Current Consumption: **{_fmt(latest['Electricity_Consumption_kWh'], ' kWh')}**")
        st.write(f"Consumption Change (vs previous 3-month average): **{_fmt(latest['Consumption_Change_Pct'], '%')}**")
        st.write(f"Anomaly Score: **{_fmt(latest['Anomaly_Score'], decimals=2)}**")
        st.write(f"Customer Type: {latest['Customer_Type']}  |  Location: {latest['Location_Type']}")
        st.caption(f"Most recent month shown: Month {int(latest['Month'])} ({latest['Data_Split']} split)")

        st.markdown("**Important Indicators:**")
        for reason in latest["Flag_Reasons"].split(";"):
            st.write(f"✓ {reason.strip()}")

        st.info(
            "This result indicates an anomalous pattern and does not prove electricity theft."
            if latest["Risk_Level"] != "Normal"
            else "This customer's consumption pattern currently looks typical."
        )

        with st.expander("View plain-text report"):
            st.code(format_customer_report(latest), language="text")

    with col2:
        st.markdown("#### Historical Consumption")
        fig, ax = plt.subplots(figsize=(6, 4))
        ax.plot(history["Month"], history["Electricity_Consumption_kWh"], marker="o", label="Actual Consumption")
        ax.plot(
            history["Month"],
            history["Average_Consumption_6_Months"],
            linestyle="--",
            marker="x",
            label="Historical Baseline (previous months only)",
        )
        ax.set_xlabel("Month")
        ax.set_ylabel("Consumption (kWh)")
        ax.legend()
        st.pyplot(fig)
        st.caption(
            "The historical baseline for Month N uses only Months 1..N-1 for that "
            "customer - it never includes the current month's own reading, and the "
            "very first month has no baseline yet (no prior data point shown)."
        )


def show_visualizations(df: pd.DataFrame):
    st.subheader("Data Visualizations")

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Consumption Distribution**")
        fig, ax = plt.subplots(figsize=(5, 3.5))
        sns.histplot(df["Electricity_Consumption_kWh"], bins=40, kde=True, ax=ax)
        ax.set_xlabel("Consumption (kWh)")
        st.pyplot(fig)

    with col2:
        st.markdown("**Anomaly Score Distribution**")
        fig, ax = plt.subplots(figsize=(5, 3.5))
        sns.histplot(df["Anomaly_Score"], bins=40, kde=True, color="orange", ax=ax)
        ax.set_xlabel("Anomaly Score")
        st.pyplot(fig)

    col3, col4 = st.columns(2)

    with col3:
        st.markdown("**Consumption by Customer Type**")
        fig, ax = plt.subplots(figsize=(5, 3.5))
        sns.boxplot(data=df, x="Customer_Type", y="Electricity_Consumption_kWh", ax=ax)
        st.pyplot(fig)

    with col4:
        st.markdown("**Risk Level by Customer Type**")
        fig, ax = plt.subplots(figsize=(5, 3.5))
        ct = pd.crosstab(df["Customer_Type"], df["Risk_Level"])
        ct = ct[[c for c in ["Normal", "Suspicious", "High Risk"] if c in ct.columns]]
        ct.plot(kind="bar", stacked=True, ax=ax, color=["#4C9A6A", "#E8B84B", "#D1495B"])
        ax.set_ylabel("Count")
        st.pyplot(fig)

    st.markdown("**Compare Customers**")
    ids = st.multiselect(
        "Select up to 5 customers to compare",
        sorted(df["Customer_ID"].unique()),
        max_selections=5,
    )
    if ids:
        subset = df[df["Customer_ID"].isin(ids)]
        fig, ax = plt.subplots(figsize=(8, 4))
        for cid in ids:
            cust_data = subset[subset["Customer_ID"] == cid].sort_values("Month")
            ax.plot(cust_data["Month"], cust_data["Electricity_Consumption_kWh"], marker="o", label=cid)
        ax.set_xlabel("Month")
        ax.set_ylabel("Consumption (kWh)")
        ax.legend()
        st.pyplot(fig)


def show_model_comparison():
    st.subheader("Model Comparison")
    st.caption(
        "All models are evaluated on the same held-out TEST months (5–6) — genuinely "
        "unseen data none of the models were trained or fit on."
    )

    comparison = load_comparison_table()
    if comparison is None:
        st.warning(
            "Comparison table not found. Run `python src/evaluate_model.py` after "
            "training to generate `data/model_comparison.csv`."
        )
        return

    st.dataframe(comparison, use_container_width=True, hide_index=True)

    st.markdown(
        """
        - **Isolation Forest** — primary, unsupervised, no labels needed.
        - **One-Class SVM** — unsupervised comparison; traded lower precision for
          much higher recall in this run.
        - **Random Forest** — supervised benchmark, only possible because this
          *synthetic* dataset has a ground-truth label. Not the primary model —
          in a real deployment this label usually wouldn't exist.
        - **Simple Rule Baseline** — no ML at all, just fixed thresholds on
          consumption change/deviation. Included to answer *"why use ML instead
          of a simple rule?"* with real numbers rather than an assumption.
        - **PR-AUC** summarizes performance across *all* thresholds at once (rank-based).
          It's `N/A` for the baseline since a fixed rule has only one operating
          point, not a ranked score to sweep across thresholds.
        """
    )

    summary = load_eval_summary()
    if summary is None:
        return

    st.markdown("---")
    st.markdown("### Error Analysis (Isolation Forest, primary model)")
    err = summary["error_analysis"]

    col1, col2 = st.columns(2)
    col1.metric("False Positives (test months)", err["false_positive_count"])
    col2.metric("False Negatives (test months)", err["false_negative_count"])

    st.markdown(
        f"""
        | Error Type | Observation from this run |
        |---|---|
        | False Positive | Avg. consumption variability is higher ({err['fp_avg_variability']}) than true negatives ({err['tn_avg_variability']}) — naturally volatile customers get over-flagged. |
        | False Positive | {err['fp_customer_type_counts']} — concentrated in one customer type, whose larger absolute swings look anomalous even when normal. |
        | False Negative | Avg. consumption drop ({err['fn_avg_change_pct']}%) is milder than caught cases ({err['tp_avg_change_pct']}%) — subtle theft patterns blend into normal variation. |
        | False Negative | {err['fn_customer_type_counts']} — concentrated in one customer type, where a given kWh drop is a smaller *relative* change. |
        """
    )
    st.caption(
        "These are descriptive observations from this specific run, not a claim that "
        "these factors *cause* every error — see README 'Error Analysis' section for detail."
    )


if __name__ == "__main__":
    main()
