"""
evaluate_model.py
--------------------
Evaluates the trained models on the TEST months (5-6) only - the
genuinely unseen data that none of the models (including the scaler
and imputation statistics) were fit on. This is the standard
train/test evaluation setup, applied here in a time-aware way because
of how the dataset is structured (see data_preprocessing.py).

IMPORTANT LIMITATION OF ANOMALY-DETECTION EVALUATION:
Isolation Forest and One-Class SVM are UNSUPERVISED - they never see
the ground-truth label during training. In a real deployment we would
usually have NO reliable ground truth at all, and evaluation would
rely on manual inspection feedback over time. Because our project uses
SYNTHETIC data, we do have a ground-truth "Theft_Flag_GroundTruth"
column (simulating past investigation outcomes), so we use it here
ONLY for evaluation - never for training - to see how the model's
flags line up with the simulated theft patterns.

HONESTY NOTE: because the ground-truth patterns were generated by our
own synthetic-data script (src/generate_dataset.py), these numbers
measure how well the models recover the SIMULATED anomalous patterns
we injected - NOT real-world electricity-theft detection accuracy.
Real consumption data, real tampering techniques, and real noise would
likely look different, so these results should be read as a
demonstration of methodology, not a production performance guarantee.

We deliberately do NOT focus on accuracy alone, because the classes
are heavily imbalanced (theft cases are rare). A model that predicts
"Normal" for everyone would already have high accuracy while being
completely useless. Precision, recall, F1-score and the confusion
matrix give a much more honest picture.
"""

import os
import joblib
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    average_precision_score,
)


def evaluate_isolation_forest(test_df: pd.DataFrame):
    """
    Compare Isolation Forest's binary anomaly flag against ground truth,
    ON THE TEST SPLIT ONLY (months 5-6 - never seen during training).
    IsolationForest_Prediction: -1 = anomaly, 1 = normal -> convert to 1/0.
    """
    y_true = test_df["Theft_Flag_GroundTruth"]
    y_pred = (test_df["IsolationForest_Prediction"] == -1).astype(int)
    return _score_block("Isolation Forest (test months 5-6)", y_true, y_pred)


def evaluate_one_class_svm(test_df: pd.DataFrame):
    y_true = test_df["Theft_Flag_GroundTruth"]
    y_pred = (test_df["OneClassSVM_Prediction"] == -1).astype(int)
    return _score_block("One-Class SVM (test months 5-6)", y_true, y_pred)


def evaluate_random_forest(rf_model, rf_test_data):
    """Evaluated on the same time-based test split (months 5-6)."""
    X_test, y_test = rf_test_data
    y_pred = rf_model.predict(X_test)
    return _score_block("Random Forest (test months 5-6, supervised)", y_test, y_pred)


def evaluate_baseline_rule(test_df: pd.DataFrame):
    """
    Evaluate the simple non-ML baseline (see baseline_model.py) on the
    exact same test months, so it can be fairly compared against the
    three trained models. Answers "why use ML instead of a simple
    rule?" with an actual number instead of an assumption.
    """
    y_true = test_df["Theft_Flag_GroundTruth"]
    y_pred = test_df["Baseline_Prediction"]
    return _score_block("Simple Rule Baseline (test months 5-6, no ML)", y_true, y_pred)


def compute_pr_auc(models_dir: str, test_df: pd.DataFrame) -> dict:
    """
    Compute PR-AUC (average precision) for the models that produce a
    continuous, rankable score - Isolation Forest, One-Class SVM, and
    Random Forest. PR-AUC summarizes performance across ALL possible
    thresholds at once, which is a fairer comparison than a single
    accuracy/precision/recall triple computed at one fixed threshold,
    and is especially informative here because the positive class
    (theft) is rare.

    PR-AUC is rank-based (invariant to any monotonic rescaling of the
    score), so we can use each model's RAW score directly - there's no
    need to reuse the leak-safe 0-1 anomaly-score normalization for
    this particular metric.

    The simple rule baseline is intentionally EXCLUDED here: it only
    ever outputs a hard 0/1 flag, not a ranked score, so "PR-AUC" isn't
    a meaningful concept for it (there's only one operating point to
    evaluate, not a curve across thresholds) - reported as "N/A" rather
    than a fabricated number.
    """
    from feature_engineering import ENGINEERED_FEATURES

    scaler = joblib.load(os.path.join(models_dir, "scaler.pkl"))
    iso_model = joblib.load(os.path.join(models_dir, "isolation_forest.pkl"))
    ocsvm_model = joblib.load(os.path.join(models_dir, "one_class_svm.pkl"))
    rf_model = joblib.load(os.path.join(models_dir, "random_forest.pkl"))

    X_test = test_df[ENGINEERED_FEATURES]
    X_test_scaled = scaler.transform(X_test)
    y_true = test_df["Theft_Flag_GroundTruth"]

    iso_raw = -iso_model.score_samples(X_test_scaled)          # higher = more anomalous
    ocsvm_raw = -ocsvm_model.decision_function(X_test_scaled)  # higher = more anomalous
    rf_proba = rf_model.predict_proba(X_test)[:, 1]            # P(theft)

    return {
        "Isolation Forest": round(average_precision_score(y_true, iso_raw), 3),
        "One-Class SVM": round(average_precision_score(y_true, ocsvm_raw), 3),
        "Random Forest": round(average_precision_score(y_true, rf_proba), 3),
        "Simple Rule Baseline": None,  # not applicable - see docstring
    }


def error_analysis(test_df: pd.DataFrame, n_examples: int = 3) -> dict:
    """
    Simple error analysis for the PRIMARY model (Isolation Forest) on
    the test months. No new "explainability system" - just descriptive
    statistics comparing false positives/negatives against the rest of
    the test set, using features that already exist.
    """
    y_true = test_df["Theft_Flag_GroundTruth"]
    y_pred = (test_df["IsolationForest_Prediction"] == -1).astype(int)

    fp_mask = (y_true == 0) & (y_pred == 1)
    fn_mask = (y_true == 1) & (y_pred == 0)
    tn_mask = (y_true == 0) & (y_pred == 0)
    tp_mask = (y_true == 1) & (y_pred == 1)

    cols = ["Customer_ID", "Month", "Customer_Type", "Electricity_Consumption_kWh",
            "Consumption_Change_Pct", "Consumption_Variability", "Power_Factor", "Anomaly_Score"]

    fp_examples = test_df.loc[fp_mask, cols].head(n_examples).to_dict("records")
    fn_examples = test_df.loc[fn_mask, cols].head(n_examples).to_dict("records")

    def _safe_mean(mask, col):
        vals = test_df.loc[mask, col]
        return round(float(vals.mean()), 3) if len(vals) else None

    summary = {
        "false_positive_count": int(fp_mask.sum()),
        "false_negative_count": int(fn_mask.sum()),
        "fp_avg_variability": _safe_mean(fp_mask, "Consumption_Variability"),
        "tn_avg_variability": _safe_mean(tn_mask, "Consumption_Variability"),
        "fn_avg_change_pct": _safe_mean(fn_mask, "Consumption_Change_Pct"),
        "tp_avg_change_pct": _safe_mean(tp_mask, "Consumption_Change_Pct"),
        "fp_customer_type_counts": test_df.loc[fp_mask, "Customer_Type"].value_counts().to_dict(),
        "fn_customer_type_counts": test_df.loc[fn_mask, "Customer_Type"].value_counts().to_dict(),
    }

    print(f"\n===== Error Analysis (Isolation Forest, test months 5-6) =====")
    print(f"False Positives: {summary['false_positive_count']} | False Negatives: {summary['false_negative_count']}")
    print(
        f"Avg Consumption_Variability -> False Positives: {summary['fp_avg_variability']}, "
        f"True Negatives: {summary['tn_avg_variability']} "
        f"(FPs tend to have {'higher' if (summary['fp_avg_variability'] or 0) > (summary['tn_avg_variability'] or 0) else 'similar/lower'} natural variability)"
    )
    print(
        f"Avg Consumption_Change_Pct -> False Negatives: {summary['fn_avg_change_pct']}, "
        f"True Positives: {summary['tp_avg_change_pct']} "
        f"(FNs missed because their drop was {'milder' if (summary['fn_avg_change_pct'] or 0) > (summary['tp_avg_change_pct'] or 0) else 'similar'} than caught cases)"
    )
    print("\nExample False Positives (flagged but actually normal):")
    for ex in fp_examples:
        print(f"  {ex}")
    print("\nExample False Negatives (missed actual theft cases):")
    for ex in fn_examples:
        print(f"  {ex}")

    return summary


def _score_block(model_name, y_true, y_pred, verbose=True):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    cm = confusion_matrix(y_true, y_pred)

    if verbose:
        print(f"\n===== {model_name} =====")
        print(f"Accuracy : {acc:.3f}")
        print(f"Precision: {prec:.3f}  (of predicted anomalies, how many were real theft cases)")
        print(f"Recall   : {rec:.3f}  (of real theft cases, how many did we catch)")
        print(f"F1-score : {f1:.3f}")
        print("Confusion Matrix [ [TN, FP], [FN, TP] ]:")
        print(cm)

        if cm.size == 4:
            tn, fp, fn, tp = cm.ravel()
            print(f"False Positives: {fp} (normal customers incorrectly flagged - investigation time wasted)")
            print(f"False Negatives: {fn} (actual theft cases missed - revenue loss continues)")

    return {"model": model_name, "accuracy": acc, "precision": prec, "recall": rec, "f1": f1, "confusion_matrix": cm}


def class_imbalance_report(df: pd.DataFrame, split_name="all"):
    counts = df["Theft_Flag_GroundTruth"].value_counts()
    total = len(df)
    print(f"\n===== Class Imbalance ({split_name}) =====")
    print(f"Normal records : {counts.get(0, 0)} ({100 * counts.get(0, 0) / total:.2f}%)")
    print(f"Theft records  : {counts.get(1, 0)} ({100 * counts.get(1, 0) / total:.2f}%)")
    print("This imbalance is why accuracy alone is misleading, and why we")
    print("focus on recall (catching real theft) and precision (avoiding false alarms).")


def build_comparison_table(results: list, pr_auc: dict = None) -> pd.DataFrame:
    """Build the Model / Accuracy / Precision / Recall / F1 (/ PR-AUC) comparison table from actual results."""
    rows = []
    for r in results:
        row = {
            "Model": r["model"],
            "Accuracy": round(r["accuracy"], 3),
            "Precision": round(r["precision"], 3),
            "Recall": round(r["recall"], 3),
            "F1-Score": round(r["f1"], 3),
        }
        if pr_auc is not None:
            # Match on the short model name embedded at the start of r["model"]
            for key, value in pr_auc.items():
                if r["model"].startswith(key):
                    row["PR-AUC"] = value if value is not None else "N/A"
                    break
        rows.append(row)
    return pd.DataFrame(rows)


def customer_level_summary(df: pd.DataFrame) -> dict:
    """
    Summarize risk at the CUSTOMER level rather than the customer-MONTH
    (record) level. The dataset has multiple rows per customer (one per
    month), so "flagged records / total records" is NOT the same as
    "flagged customers / total customers" - conflating the two produces
    a misleading rate. See README section "Customer-Level vs
    Record-Level Analysis" for a worked example.
    """
    total_customers = df["Customer_ID"].nunique()
    suspicious_customers = df.loc[df["Risk_Level"] == "Suspicious", "Customer_ID"].nunique()
    high_risk_customers = df.loc[df["Risk_Level"] == "High Risk", "Customer_ID"].nunique()
    flagged_customers = df.loc[df["Risk_Level"].isin(["Suspicious", "High Risk"]), "Customer_ID"].nunique()

    return {
        "total_customers": total_customers,
        "customers_with_suspicious_month": suspicious_customers,
        "customers_with_high_risk_month": high_risk_customers,
        "customers_flagged_at_least_once": flagged_customers,
        "customer_risk_rate_pct": round(100 * flagged_customers / total_customers, 2) if total_customers else 0.0,
    }


def record_level_summary(df: pd.DataFrame) -> dict:
    """Summarize risk at the customer-MONTH (record) level."""
    total_records = len(df)
    counts = df["Risk_Level"].value_counts()
    normal = int(counts.get("Normal", 0))
    suspicious = int(counts.get("Suspicious", 0))
    high_risk = int(counts.get("High Risk", 0))
    return {
        "total_records": total_records,
        "normal_records": normal,
        "suspicious_records": suspicious,
        "high_risk_records": high_risk,
        "record_anomaly_rate_pct": round(100 * (suspicious + high_risk) / total_records, 2) if total_records else 0.0,
    }


if __name__ == "__main__":
    import joblib

    base_dir = os.path.dirname(__file__)
    data_path = os.path.join(base_dir, "..", "data", "scored_customers.csv")
    models_dir = os.path.join(base_dir, "..", "models")

    df = pd.read_csv(data_path)
    test_df = df[df["Data_Split"] == "Test"].copy()

    print(f"Full dataset: {len(df)} customer-month records ({df['Customer_ID'].nunique()} unique customers)")
    print(f"Evaluating on TEST months only: {len(test_df)} records")

    class_imbalance_report(test_df, split_name="test months 5-6")

    iso_result = evaluate_isolation_forest(test_df)
    svm_result = evaluate_one_class_svm(test_df)
    baseline_result = evaluate_baseline_rule(test_df)

    # Reload the trained Random Forest + rebuild its exact time-based test split for a clean, honest evaluation
    from feature_engineering import ENGINEERED_FEATURES

    rf_model = joblib.load(os.path.join(models_dir, "random_forest.pkl"))
    X_test = test_df[ENGINEERED_FEATURES]
    y_test = test_df["Theft_Flag_GroundTruth"]
    rf_result = evaluate_random_forest(rf_model, (X_test, y_test))

    pr_auc = compute_pr_auc(models_dir, test_df)
    print("\n===== PR-AUC (rank-based, all thresholds at once) =====")
    for model_name, value in pr_auc.items():
        print(f"{model_name}: {value if value is not None else 'N/A (hard rule, no ranked score)'}")

    print("\n\n===== Model Comparison Table (test months 5-6, actual results) =====")
    comparison = build_comparison_table([iso_result, svm_result, rf_result, baseline_result], pr_auc=pr_auc)
    print(comparison.to_string(index=False))

    print("\n\n===== Record-Level Summary (all months, from the scored dataset) =====")
    rec_summary = record_level_summary(df)
    print(rec_summary)

    print("\n===== Customer-Level Summary (all months, from the scored dataset) =====")
    cust_summary = customer_level_summary(df)
    print(cust_summary)

    err_summary = error_analysis(test_df)

    # ---- Save a small summary artifact so the Streamlit dashboard can ----
    # ---- display the comparison table / error analysis WITHOUT reloading ----
    # ---- every model itself (keeps the dashboard fast and simple).
    comparison.to_csv(os.path.join(models_dir, "..", "data", "model_comparison.csv"), index=False)
    joblib.dump(
        {"record_level": rec_summary, "customer_level": cust_summary, "error_analysis": err_summary},
        os.path.join(models_dir, "evaluation_summary.pkl"),
    )
    print("\nSaved comparison table to data/model_comparison.csv")
    print("Saved evaluation summary to models/evaluation_summary.pkl")
